services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      # SQLite persists in ./data 
      - ./data:/app/data
    expose:
      - "5000"     # internal only; nginx talks to this
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/"]
      interval: 10s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "8080:80"  
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
